### ISSUE TITLE
.pom file does not include dependencies

### ISSUE THREAD

**Issue by shevek** [etiennestuder/gradle-plugindev-plugin#11]
The generated .pom file does not appear to include the dependencies of the module project. Previous publications set up by hand using Nexus, e.g. gradle-velocity-plugin, have not had this trouble.

To reproduce:

clone https://github.com/shevek/gradle-jnaerator-plugin
run ./gradlew --daemon publishPluginPublicationToMavenLocal
clone git@github.com:shevek/udev4j.git
run ./gradlew --daemon jar

**Comment by etiennestuder** [comment]
This is related to how the 'maven-publish' plugin works in Gradle. I have added a section to the README.md for people to be aware of. Thanks for pointing this out.
