### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by IlyaGazman** [etiennestuder/gradle-plugindev-plugin#15]
Could not upload to 'myfile.jar': HTTP/1.1 401 Unauthorized

I am sure that the username and api key are well spelled. Any ideas why is this happen?

**Comment by moleksyuk** [comment]
@IlyaGazman it works fine for me.
Make sure you are using **API Key** instead of account password.

![untitled](https://cloud.githubusercontent.com/assets/793472/5773759/b2e31ba2-9d6e-11e4-9e1e-4b2bf915af74.png)

**Comment by etiennestuder** [comment]
Hi Ilya, I'm not aware of any upload problems related to the plugindev plugin itself. The actual uploading is delegated to the Bintray plugin. The error message indicates that the upload location is 'myfile.jar' (rather than some URL) which seems very strange. Bumping up the log level to debug might give you some more insights. A pointer to your build script might help as well so someone else can take a look at your script. 
Regards, Etienne

**Comment by ysb33r** [comment]
>  Could not upload to 'myfile.jar': HTTP/1.1 401 Unauthorized
> 
> I am sure that the username and api key are well spelled. Any ideas why is this happen?

@IlyaGazman Are you trying to publish a SNAPSHOT?

**Comment by IlyaGazman** [comment]
@moleksyuk  Yeah I got this part right. 

@etiennestuder At first I got this error:

Could not create package 'Fuzz-Productions/gradle-plugins/Skeleton': HTTP/1.1 401 Unauthorized

After creating the package and the version manually, I got the error that I logged in the question. 
Here is my script. May be it will provide some clue to why this is happening:

apply plugin: 'java'
apply plugin: 'nu.studer.plugindev'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'nu.studer:gradle-plugindev-plugin:1.0.3'
        classpath 'org.codehaus.groovy:groovy-backports-compat23:2.3.5'
    }
}

configurations {
    deployerJars
}

dependencies {
    compile gradleApi()
    compile 'com.android.tools.build:gradle:0.12.+'
}

group = 'com.fuzz.skeleton'
version = '1.0.0.R'

plugindev {
    pluginImplementationClass 'com.fuzz.skeleton.Main'
    pluginDescription 'Gradle plugin for automaticaly generate ViewHolder files.'
    pluginLicenses 'Apache-2.0'
    pluginTags 'gradle', 'plugin', 'skeleton', 'android', 'resources', 'files'
    authorId 'Ilya'
    authorName 'Ilya Gazman'
    authorEmail 'igazman@fuzzproductions.com'
    projectUrl 'https://github.com/fuzz-productions/skeleton'
    projectInceptionYear '2015'
    pomConfiguration {
        licenses {
            license {
                name 'MPL'
                url 'http://static.fuzzhq.com/licenses/MPL'
            }
        }
    }
    done() // do not omit this
}

bintray {
    user = "$BINTRAY_USER"
    key = "$BINTRAY_API_KEY"
    pkg.repo = 'gradle-plugins'
}

**Comment by IlyaGazman** [comment]
Also it is important to mention that I am trying to upload to Organizations repo where I am Admin but not the owner. I also been trying to use the owner api key and got the same error.

**Comment by IlyaGazman** [comment]
I found my problem and successfully uploaded. I had to add userOrg = 'fuzz-productions'.  in bintray pkg

**Comment by etiennestuder** [comment]
Glad that you were able to solve the issue.
