### ISSUE TITLE
Duplicated *.properties file in META-INF/gradle-plugins

### ISSUE THREAD

**Issue by moleksyuk** [etiennestuder/gradle-plugindev-plugin#16]
Hi @etiennestuder 

According to official documentation for custom plugins [Section 59.5. A standalone project](http://www.gradle.org/docs/current/userguide/custom_plugins.html) developer has to provide property files in META-INF/gradle-plugins folder:

>>So how does Gradle find the Plugin implementation? The answer is you need to provide a properties file in the jar's META-INF/gradle-plugins directory that matches the id of your plugin.

>>Example 59.6. Wiring for a custom plugin

>>src/main/resources/META-INF/gradle-plugins/org.samples.greeting.properties 
>>implementation-class=org.gradle.GreetingPlugin

Your plugin will generate it if it's missed BUT if it exists that jar file will have 2 files:

![screenshot - 16-jan-2015 11_10_14](https://cloud.githubusercontent.com/assets/793472/5773901/7cd79040-9d70-11e4-9f91-fdd978c74f69.png)

One of the file has original content:
```
implementation-class=com.github.moleksyuk.plugin.SemanticVersionPlugin
```

And generated:
```
implementation-class=com.github.moleksyuk.plugin.SemanticVersionPlugin
implementation-version=1.0.0
```

If you try to unzip it you won't get two files on file system with the same file but jar contains them. Seems like it's a jar **feature** :smile: 

I don't think it's a critical because both of them have definition of plugin implementation class but probably you should fix this anyway.

**Comment by etiennestuder** [comment]
Hi

Thanks for the feedback. The assumption is that the user does _not_ generate the plugin descriptor file himself but instead lets the plugin generate it.

I could cover the case where the descriptor already exists (like you describe it) but considering that this is not an intended usage scenario, I cannot afford the little time I have to support such a scenario. A PR would be welcome, though ;-)

Regards, Etienne

**Comment by etiennestuder** [comment]
Closing this issue since it is a border-case that does not happen under 'normal' circumstances. Can be fixed through a PR, if really needed.
