### ISSUE TITLE
Error:Could not find ihrthk.droidsonroids.gradle.localization:android-gradle-localization-plugin:1.0.8 

### ISSUE THREAD

**Issue by ihrthk** [etiennestuder/gradle-plugindev-plugin#17]
I use plugindev plugin pushlish to bintray.com,But i can't download it.How i fix resolve it?

error log:

Error:Could not find ihrthk.droidsonroids.gradle.localization:android-gradle-localization-plugin:1.0.8.
Searched in the following locations:
    file:/D:/Program Files (x86)/android-studio/gradle/m2repository/ihrthk/droidsonroids/gradle/localization/android-gradle-localization-plugin/1.0.8/android-gradle-localization-plugin-1.0.8.pom
    file:/D:/Program Files (x86)/android-studio/gradle/m2repository/ihrthk/droidsonroids/gradle/localization/android-gradle-localization-plugin/1.0.8/android-gradle-localization-plugin-1.0.8.jar
    https://jcenter.bintray.com/ihrthk/droidsonroids/gradle/localization/android-gradle-localization-plugin/1.0.8/android-gradle-localization-plugin-1.0.8.pom
    https://jcenter.bintray.com/ihrthk/droidsonroids/gradle/localization/android-gradle-localization-plugin/1.0.8/android-gradle-localization-plugin-1.0.8.jar
Required by:
    :VideoPlayer:unspecified

config:
 classpath 'ihrthk.droidsonroids.gradle.localization:android-gradle-localization-plugin:1.0.8'

address:
https://bintray.com/ihrthk/groovy-plugins/android-gradle-localization-plugin/1.0.8/view

**Comment by etiennestuder** [comment]
Cannot reproduce this issue. And the bintray link is invalid.
