### ISSUE TITLE
Multiple plugins in a single JAR

### ISSUE THREAD

**Issue by muryoh** [etiennestuder/gradle-plugindev-plugin#19]
Hello,

I've been using your plugin for a few plugins and it is working fine :) Thanks for that!

However I recently wanted to bundle more than one plugin in a same JAR and the current implementation does not allow that.

Is that on purpose?
I'd gladly submit a PR to have it working for multiple plugins.

Cheers

**Comment by etiennestuder** [comment]
Hi

You are right. The plugindev plugin currently does not support bundling multiple plugins since this case does not happen too often. I'd be happy for receive a PR to support bundling multiple plugins.

Regards, Etienne

**Comment by etiennestuder** [comment]
Given that today, the plugin recommended by default is the [plugin publishing plugin](https://plugins.gradle.org/docs/submit) from Gradle, further extensions of the functionality of the plugindev plugin are not planned.
