### ISSUE TITLE
Plugin breaks tests in nebula

### ISSUE THREAD

**Issue by marcingrzejszczak** [etiennestuder/gradle-plugindev-plugin#23]
Maybe I've done sth wrong but If you write test in [nebula-test](https://github.com/nebula-plugins/nebula-test) you need to have the `META-INF/gradle-plugins` entry for the nebula project to see that your plugin is available.

If one uses this plugin he will not have this file created before tests and if it's there the tests don't seem to see the plugin descriptor.

There is a workaround for Gradle though:

```
task copyPluginDescriptorToMetaInf(type: Copy, dependsOn: generatePluginDescriptorFile) {
    from "$project.buildDir/plugindev"
    into "${sourceSets.main.output.resourcesDir}/META-INF/gradle-plugins"
}

test.dependsOn copyPluginDescriptorToMetaInf
```

How do you think it would be possible to add this functionality to your plugin? Some switch maybe like

```
copyDescriptorToBuildFolder = true
```

The problem still remains for running tests from IDE.

**Comment by etiennestuder** [comment]
Hi Marcin
This should be resolved with the current master (see https://github.com/etiennestuder/gradle-plugindev-plugin/issues/3). I plan to release master as 1.0.4 later this week. If you want to try out master and see if it fixes your problem, too, that would be great. (it will not fix the IDE case though)
Regards, Etienne

**Comment by marcingrzejszczak** [comment]
Tested against 1.0.4.DEV and I confirm that it's working properly.

**Comment by etiennestuder** [comment]
Thanks for your confirmation, Marc.
