### ISSUE TITLE
Update to new gradle-bintray-plugin that supports gradle 2.4

### ISSUE THREAD

**Issue by sparkym3** [etiennestuder/gradle-plugindev-plugin#26]
Please update to new gradle-bintray-plugin that supports gradle 2.4 once it is available per this issue
https://github.com/bintray/gradle-bintray-plugin/issues/70

**Comment by sparkym3** [comment]
It looks like the version 1.2 is out and resolves the gradle 2.4 issue. This will take a funny build path or I would create pulls for you. You will need to build against the 1.2 with the old gradle, and then use that build version to build this project against gradle 2.4.

**Comment by dlew** [comment]
Workaround until update: You can just include the latest gradle-bintray-plugin with plugindev:

```gradle
plugins {
    id 'nu.studer.plugindev' version '1.0.3'
    id 'com.jfrog.bintray' version '1.2'
}
```

**Comment by etiennestuder** [comment]
Version 1.0.4 has been upgrade to gradle-bintray-plugin 1.2
