### ISSUE TITLE
Add property to configure dryRun for bintrayUpload

### ISSUE THREAD

**Issue by friedger** [etiennestuder/gradle-plugindev-plugin#28]
dryRun property is set to false. When running on CI server it might be good to have dry runs.

**Comment by dlew** [comment]
I was able to configure `dryRun` through the `bintray` plugin via this plugin, using this: https://github.com/etiennestuder/gradle-plugindev-plugin#configure-bintray-plugin

**Comment by etiennestuder** [comment]
You can configure this in the Bintray DSL, as mentioned by @dlew. If you need to inject different values, you can do this through a project property, for example.

bintray {
    user = ...
    key = ...
    pkg.repo = ...
    dryRun = true
}
