### ISSUE TITLE
pom: issue management

### ISSUE THREAD

**Issue by TheBoegl** [etiennestuder/gradle-plugindev-plugin#33]
The generated pom file should contain a `issueManagement` section (see [Section Issue Management](https://maven.apache.org/pom.html#Issue_Management)).

For github the defaults would be
```
issueManagement {
    system 'github'
    url extension.projectIssuesUrl
}
```

**Comment by etiennestuder** [comment]
I've added issueManagement.url. This will be available in 1.0.9. I do not have the time to put more work into this right now.
