### ISSUE TITLE
Incompatible with Gradle 4.8 and latest bintray plugin

### ISSUE THREAD

**Issue by ngyukman** [etiennestuder/gradle-plugindev-plugin#34]
latest bintray plugin has changed the namespace of the BintrayUploadTask to 
https://github.com/bintray/gradle-bintray-plugin/blob/3fe02dfdae3e807afba57e0140a0d4c2424674e1/src/main/groovy/com/jfrog/bintray/gradle/tasks/BintrayUploadTask.groovy

**Comment by etiennestuder** [comment]
I've released a new version 1.0.7 that is compiled against Gradle 4.10.3 and gradle-bintray-plugin 1.8.4.

**Comment by ngyukman** [comment]
thanks a lot
